INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 email,
 twitter,
 instagram,
 picture_name,
 picture_num)
VALUES (
 1,
 '東北大学学友会競技舞踏部',
 '学友会体育部',
 '全学',
 '部員同士とても仲の良い明るい雰囲気の部です💃🕺およそ80人が所属しており、他の学部･学年との交流も多いです！男女比は１：１となってます！',
 '私たちの部では男女がペアとなり踊る競技ダンスを行っています！少し前に金スマでキンタローとロペスが挑戦していたダンスです💃🕺見覚えのある方もいるのではないでしょうか！部員はほとんどが大学から始めた初心者なのでダンスをやったことがない人でも大丈夫！みなさんも競技ダンス部で充実した大学生活を送りませんか🤗活動は週3回火木土曜日に行っています！また、今年はzoomを使用した新歓を行います！！Twitterなどで随時情報を更新しているのでぜひご覧下さい💪みなさんの入部を心よりお待ちしてます😌Twitter👉東北大学学友会競技舞踏部または@tonpei_bukenで検索！  Instagram👉  https://instagram.com/tonpei_buken?igshid=fvuozewubun7',
 '今年はzoomを使用した新歓を行っています！次は5月5日(火)19時~を予定しています！参加してくれた方にはAmazonギフトをプレゼントします！ぜひ気軽に参加してください！',
 'dubianxiahai55@gmail.com',
 'https://twitter.com/tonpei_buken',
 'https://instagram.com/tonpei_buken?igshid=fvuozewubun7',
 '東北大学競技舞踏部',
 3);
 INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 email,
 twitter,
 instagram,
 picture_name,
 picture_num)
VALUES (
 2,
 '東北大学漫画研究会',
 '非学友会(サークル)',
 '全学',
 '各学年10人前後、男女比:7:3',
 '東北大学漫画研究会では、主に「漫画を読む・描く」という活動を中心にしているサークルです。  漫研の部室内には様々な世代・ジャンルの漫画が沢山置かれており、部員は読み放題です。また、ルパと呼ばれるノートに旨を記入すればその漫画を借りることができます。  サークルでは展示会や部誌の発行を行っており、どちらも年2回のペースです。ここではオリジナルの漫画作品を各自提出することになります。 漫画はアナログ・デジタルどちらもOKで、初心者さんには先輩が各タイプの描き方を教えます！  その他にも、コンパや芋煮会などの部員同士が交流できる楽しいイベントも！是非入部を検討してみてくださいね！！',
 '例年ver 4月:お花見、新歓コンパ 6月:展示会(水無月展) 5月:川渡合宿(三日間) 7月:帰省コン 8月:夏季部誌発行、夏コミ 9月:芋煮会 11月:展示会(学祭)、突コン 12月:忘年会、冬コミ 2月:冬季部誌発行、追いコン',
 null,
 'https://twitter.com/tohoku_manken',
 null,
 '東北大学漫画研究会',
 1);
 INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 email,
 twitter,
 instagram,
 picture_name,
 picture_num)
VALUES (
 3,
 '東北大学祭事務局',
 'その他',
 'インターカレッジ',
 '1.2年生で構成されるひと学年100人程の団体です！',
 '東北大学祭の運営',
 'zoom新歓を5/3.5.6.8.11.14.16.17に17:00からやる予定です。TwitterにLINEオープンチャットのQRも貼ってあります！よかったらご参加ください！',
 'festatohokushinkan2020@gmail.com',
 'https://twitter.com/tohoku_festa',
 null,
 '東北大学祭事務局',
 3);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 email,
 twitter,
 instagram,
 picture_name,
 picture_num)
VALUES (
 4,
'東北大学学友会軟式野球部',
'学友会体育部',
'全学',
'プレイヤー25人マネージャー1人 メリハリをつけた活動がモットー',
'火木土川内グラウンドにて活動中,マネージャー、プレイヤー共に大募集してます！',
'オンラインによる人狼、クイズ大会新歓を行っております。',
null,
'https://twitter.com/tonpeinanya',
null,
'東北大学学友会軟式野球部',
1
);