INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 1,
 '東北大学 学友会 競技舞踏部',
 '学友会体育部',
 '全学',
 '部員同士とても仲の良い明るい雰囲気の部です💃🕺およそ80人が所属しており、他の学部･学年との交流も多いです！男女比は１：１となってます！',
 '私たちの部では男女がペアとなり踊る競技ダンスを行っています！少し前に金スマでキンタローとロペスが挑戦していたダンスです💃🕺見覚えのある方もいるのではないでしょうか！部員はほとんどが大学から始めた初心者なのでダンスをやったことがない人でも大丈夫！みなさんも競技ダンス部で充実した大学生活を送りませんか🤗活動は週3回火木土曜日に行っています！また、今年はzoomを使用した新歓を行います！！Twitterなどで随時情報を更新しているのでぜひご覧下さい💪みなさんの入部を心よりお待ちしてます',
 '今年はzoomを使用した新歓を行っています！次は5月5日(火)19時~を予定しています！参加してくれた方にはAmazonギフトをプレゼントします！ぜひ気軽に参加してください！',
 null,
 'dubianxiahai55@gmail.com',
 'https://twitter.com/tonpei_buken',
 'https://instagram.com/tonpei_buken?igshid=fvuozewubun7',
 null,
 '東北大学競技舞踏部',
 3);
 INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 2,
 '東北大学 漫画研究会',
 '非学友会(サークル)',
 '全学',
 '各学年10人前後、男女比:7:3',
 '東北大学漫画研究会では、主に「漫画を読む・描く」という活動を中心にしているサークルです。  漫研の部室内には様々な世代・ジャンルの漫画が沢山置かれており、部員は読み放題です。また、ルパと呼ばれるノートに旨を記入すればその漫画を借りることができます。  サークルでは展示会や部誌の発行を行っており、どちらも年2回のペースです。ここではオリジナルの漫画作品を各自提出することになります。 漫画はアナログ・デジタルどちらもOKで、初心者さんには先輩が各タイプの描き方を教えます！  その他にも、コンパや芋煮会などの部員同士が交流できる楽しいイベントも！是非入部を検討してみてくださいね！！',
 '例年ver 4月:お花見、新歓コンパ 6月:展示会(水無月展) 5月:川渡合宿(三日間) 7月:帰省コン 8月:夏季部誌発行、夏コミ 9月:芋煮会 11月:展示会(学祭)、突コン 12月:忘年会、冬コミ 2月:冬季部誌発行、追いコン',
 null,
 null,
 'https://twitter.com/tohoku_manken',
 null,
 null,
 '東北大学漫画研究会',
 1);
 INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 3,
 '東北大学祭事務局',
 'その他',
 'インターカレッジ',
 '1.2年生で構成されるひと学年100人程の団体です！',
 '東北大学祭の運営',
 'zoom新歓を5/3.5.6.8.11.14.16.17に17:00からやる予定です。TwitterにLINEオープンチャットのQRも貼ってあります！よかったらご参加ください！',
 null,
 'festatohokushinkan2020@gmail.com',
 'https://twitter.com/tohoku_festa',
 null,
 null,
 '東北大学祭事務局',
 3);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 4,
'東北大学 学友会 軟式野球部',
'学友会体育部',
'全学',
'プレイヤー25人マネージャー1人 メリハリをつけた活動がモットー',
'火木土川内グラウンドにて活動中,マネージャー、プレイヤー共に大募集してます！',
'オンラインによる人狼、クイズ大会新歓を行っております。',
null,
null,
'https://twitter.com/tonpeinanya',
null,
null,
'東北大学学友会軟式野球部',
1
);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 5,
'競技麻雀同好会',
'学友会文化部準加盟団体',
'全学',
'定例会は毎週15人ほどが集まっており、男性がほとんどですが女性の方もいらっしゃいます。部室での交流は後期は週に2~3回鍵が貸し出されていました。土曜日以外は暇な人が来るようなものなので月に2~3回定例会に来れる方なら十分アクティブメンバー判定になります',
'毎週土曜日13時〜17時頃:定例会(これがメイン活動です) 不定期:部室やC棟を利用した講習 日常活動:各自部室で交流 その他:年に数度の大会出場や他大学との交流。当サークルは飲まない吸わない賭けないを掲げ活動しています。全国大会に出場する強者から大学から麻雀を始めた初心者向けまで様々な層が活動しています。是非気軽に質問や訪問してみてください。',
'例年は新歓期にC棟で説明と麻雀体験をして頂き、定例会へのお試し参加もしていました。今年はコロナウイルスの影響でそれらが延期されており現状オンラインでの新歓も予定していないため活動制限が解除されるまでは特に何もありません。Twitterでの質問等はいつでも受け付けておりますので気軽にお聞きください。',
null,
'tohokumahjong@gmail.com',
'https://twitter.com/tonpei_mahjong',
null,
null,
'競技麻雀同好会',
0
);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 6,
'東北大学 学友会 合気道部',
'学友会体育部',
'全学',
'学年ごとの人数・・・4年生7名 3年生 6名 2年生 12名 他留学生2名　男女比 約2：1　現在は理、工、文学部の部員が多く在籍しています(それ以外もいます！)',
'学友会合気道部では、川内キャンパスサブアリーナ3階アリーナ2にて稽古を行っています。週6日稽古がありますが、自分のペースで活動出来ます😄 また、部員の大半が大学から合気道を始めています。武道を始めてみたい方や体を動かしたい方など、初心者大歓迎です！！もちろん経験者も大歓迎です✨ どんな部活か気になった方は気軽に連絡くださいね。Twitterにて随時情報を発信してますのでぜひご確認よろしくお願いします！ 私たちと一緒に合気道をしましょう👍',
'LINEオープンチャットで質問等受け付けています！また、Zoomを用いたオンライン説明会も行います。その他、直接何か聞きたいことがありましたら、下記の新歓メールまでお問合せください！',
null,
'tohokuaiki.welcome2020@gmail.com',
'https://twitter.com/TohokuaikiWago',
null,
null,
'東北大学学友会合気道部',
6
);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 7,
'東北大学 学友会 漕艇部',
'学友会体育部',
'全学',
'総勢83名 院生：5人（コーチ2人、新人トレーナー1人、漕手2人。男子5人） 4年生：9人（漕手7人、マネージャー2人。男子6人、女子3人） 3年生：28人（漕手20人、舵手2人、マネージャー5人、テクニカルスタッフ1人。男子20人、女子8人） 2年生：37人（漕手25人、舵手1人、マネージャー10人、コーチ1人。男子20人、女子16人） 監督、社会人コーチ：各一名 部長：1名 副部長：2名 ',
'「ボートってどんな競技？」そんな疑問を持つ新入生は多い。 答えよう！ボートとは最高にアツく、最高に成長できる場所だ。 なぜ成長できるのか。それはボート部に入ったら、全員が目標に向けて自然と努力をするからだ。努力を重ねることで、たくさんのことを学べる。それは学校での「勉強」からは、絶対に得ることの出来ない物だ。たくさんのことを学んだ君は、確実に成長している。 未経験者でも問題ないことは過去の先輩が証明済みだ。新人トレーニング期間という6ヶ月で、新人トレーナー3人が丁寧に大切に教えてくれる。 正直めっちゃ楽しい。しかも今年はコロナの影響で新人トレーニングがオンラインに移行し、期間も延長した。この状況でも新入生のことを大切に考え、臨機応変に行動している。 そんなエリート集団の仲間に君も入らないか？  せっかく東北大に入ったんだ。 一生のうち今しか出来ないことにチャレンジしてみないか？',
'5/7 チャレンジ！Zoom　｜内容：「ベタ嵐」など楽しい企画が盛り沢山！おすすめ！ 5/9 クイズ大会　｜内容：大好評企画でなんと第4回目！人気です。 5/11ボート説明会　｜内容：ボートの魅力を現役部員が紹介！主将も参加するよ！ 5/13 新レク　・・・など、更新中！ Twitterや公式サイトを見てね！ 公式LINEも開設済み！ 50人以上の新入生が追加してくれているよ！',
'https://www.tohoku-rowing.com/',
null,
'https://twitter.com/turc__2020',
null,
null,
'東北大学学友会漕艇部',
8
);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 8,
'TUSTEM',
'非学友会(サークル)',
'全学',
'留学生と日本人で構成されています。学部は主に理系学生が中心ですが、文系を含めて色々な学部の人が所属しています。',
'TUSTEMは主に理系の留学生と、日本人学生の相互の交流を目指す国際交流団体となっております🌏 毎週火曜日のディナー会、隔週木曜日の言語交換会などの交流イベントに加え、海外の大学の教授をお招きしての講演会やコーヒーイベントといったアカデミックなイベントにも力を入れています。そのほかBBQや芋煮会、クリスマスパーティーなど季節ごとのイベントもあります！ 留学生と仲良くなりたい方、留学に興味がある方は、文系理系問わず是非一度お越しください！😆',
'毎週火曜日にディナー会、隔週木曜日に言語交換会をすべてオンラインで開催しています。他にも様々なイベントを企画中ですので、ぜひTwitterをフォローして、情報をチェックしてください！',
null,
't.stem.network@gmail.com',
'https://twitter.com/StemTohoku',
null,
null,
'TUSTEM',
4
);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 9,
'東北大学 学友会 囲碁部',
'学友会文化部',
'全学',
'学部生から院生まで多くの部員が在籍しています、人数は全体で40名程度です',
'囲碁に興味を持つもの同士での対局や交流',
'zoomを利用したオンライン新歓',
null,
null,
'https://twitter.com/tompei_igo',
null,
null,
'東北大学学友会囲碁部',
null
);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 10,
'東北大学国際交流団体IPLANET ',
'その他',
'全学',
'国籍に関係なく、みんな仲が良いです。人数は150~200程度で、いろんな学部の人がいます。',
'ご入学おめでとうございます🌸  IPLANETはIPLA(International Program in Liberal Artsの略)という東北大学の留学プログラムで日本に来る留学生と交流したり、その留学生のサポートを目的とした東北大学の公式の日本人の団体です。  留学生・日本人が国籍に関係なく皆で仲良く活動しています！ 留学生のサポートをしてみたい人、留学に興味がある人、英語を上達させたい人、他の活動と両立させたい人、将来役立つ情報を知りたい人、等々、興味のある人はぜひ気軽に参加してください！ 新入生のみなさんに会えることを楽しみにしています！！',
'毎週水曜日と金曜日の夜8時から',
null,
null,
'https://twitter.com/iplanet _tohoku',
null,
null,
'IPLANET',
4
);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 11,
'ブルーグラス同好会',
'非学友会(サークル)',
'全学',
'学部1年生から修士2年生まで、100人規模のサークルです。同期間も、先輩後輩間も仲が良く、音楽を楽しむ環境があります。部員の半数は、大学から楽器を始めたので、初心者でも全く心配はいりません。また、とても自由度が高いサークルで、どのくらい活動に打ち込むかは、自分次第です。',
'ブルーグラスとは、音楽のジャンルのひとつで、アメリカで生まれたカントリー・フォークチックな音楽を指します。ギター、マンドリン、ウッドベース、バンジョー、フィドル、ドブロの６つの楽器でバンドを組み演奏します。ブルーグラス同好会のYouTubeチャンネルがあるので、どんな雰囲気の音楽か聞いてみてください！ 年間を通して、サークル内での発表会や、ブルーグラスフェスへの参加、大学祭、定期演奏会など多くの演奏機会があります。 　以下が年間予定になります。 　４月　スプリングフェスティバル 　　　新歓フリーライブ 　５月　新歓確定ライブ 　６月　部内発表会 　８月　箱根フェス、鬼ヶ城フェス 　９月　定禅寺ジャズフェス　納涼会 １０月　芋煮会 １１月　学祭 １２月　定期演奏会 　１月　新年会 　２月　駒ケ根フェス　ずんだフェス 　３月　追いコン',
'ツイッター、インスタグラム、ラインのオープンチャットにて情報を発信しています。 対面での新歓活動が解禁されれば、楽器体験等も行う予定です。',
null,
null,
'https://twitter.com/tohokubluegrass',
'https://instagram.com/tohoku.bluegrass',
null,
'ブルーグラス同好会',
5
);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 home_page,
 email,
 twitter,
 instagram,
 line,
 picture_name,
 picture_num)
VALUES (
 12,
'東北大学 学友会 演劇部',
'学友会文化部',
'全学',
'各公演ごとにおよそ20人くらいの規模で演劇を作っています。まるで毎日が文化祭！公演ごとに参加希望をとるので部員たちは自分たちのペースで演劇と関わっています！',
'演劇部は例年、年4~5回の公演を川内ホール104号室で行っています。',
'オンライン説明会 5/24,25,28,30,31全日17時から詳しくは新歓ツイッターをご覧ください。',
null,
'lastmagic913@gmail.com',
'https://twitter.com/Tonpei_drama_we',
null,
null,
'東北大学学友会演劇部',
3
);
