INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 email,
 twitter,
 instagram,
 picture_name,
 picture_num)
VALUES (
 1,
 '東北大学 学友会 競技舞踏部',
 '学友会体育部',
 '全学',
 '部員同士とても仲の良い明るい雰囲気の部です💃🕺およそ80人が所属しており、他の学部･学年との交流も多いです！男女比は１：１となってます！',
 '私たちの部では男女がペアとなり踊る競技ダンスを行っています！少し前に金スマでキンタローとロペスが挑戦していたダンスです💃🕺見覚えのある方もいるのではないでしょうか！部員はほとんどが大学から始めた初心者なのでダンスをやったことがない人でも大丈夫！みなさんも競技ダンス部で充実した大学生活を送りませんか🤗活動は週3回火木土曜日に行っています！また、今年はzoomを使用した新歓を行います！！Twitterなどで随時情報を更新しているのでぜひご覧下さい💪みなさんの入部を心よりお待ちしてます😌Twitter👉東北大学学友会競技舞踏部または@tonpei_bukenで検索！  Instagram👉  https://instagram.com/tonpei_buken?igshid=fvuozewubun7',
 '今年はzoomを使用した新歓を行っています！次は5月5日(火)19時~を予定しています！参加してくれた方にはAmazonギフトをプレゼントします！ぜひ気軽に参加してください！',
 'dubianxiahai55@gmail.com',
 'https://twitter.com/tonpei_buken',
 'https://instagram.com/tonpei_buken?igshid=fvuozewubun7',
 '東北大学競技舞踏部',
 3);
 INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 email,
 twitter,
 instagram,
 picture_name,
 picture_num)
VALUES (
 2,
 '東北大学 漫画研究会',
 '非学友会(サークル)',
 '全学',
 '各学年10人前後、男女比:7:3',
 '東北大学漫画研究会では、主に「漫画を読む・描く」という活動を中心にしているサークルです。  漫研の部室内には様々な世代・ジャンルの漫画が沢山置かれており、部員は読み放題です。また、ルパと呼ばれるノートに旨を記入すればその漫画を借りることができます。  サークルでは展示会や部誌の発行を行っており、どちらも年2回のペースです。ここではオリジナルの漫画作品を各自提出することになります。 漫画はアナログ・デジタルどちらもOKで、初心者さんには先輩が各タイプの描き方を教えます！  その他にも、コンパや芋煮会などの部員同士が交流できる楽しいイベントも！是非入部を検討してみてくださいね！！',
 '例年ver 4月:お花見、新歓コンパ 6月:展示会(水無月展) 5月:川渡合宿(三日間) 7月:帰省コン 8月:夏季部誌発行、夏コミ 9月:芋煮会 11月:展示会(学祭)、突コン 12月:忘年会、冬コミ 2月:冬季部誌発行、追いコン',
 null,
 'https://twitter.com/tohoku_manken',
 null,
 '東北大学漫画研究会',
 1);
 INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 email,
 twitter,
 instagram,
 picture_name,
 picture_num)
VALUES (
 3,
 '東北大学祭事務局',
 'その他',
 'インターカレッジ',
 '1.2年生で構成されるひと学年100人程の団体です！',
 '東北大学祭の運営',
 'zoom新歓を5/3.5.6.8.11.14.16.17に17:00からやる予定です。TwitterにLINEオープンチャットのQRも貼ってあります！よかったらご参加ください！',
 'festatohokushinkan2020@gmail.com',
 'https://twitter.com/tohoku_festa',
 null,
 '東北大学祭事務局',
 3);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 email,
 twitter,
 instagram,
 picture_name,
 picture_num)
VALUES (
 4,
'東北大学 学友会 軟式野球部',
'学友会体育部',
'全学',
'プレイヤー25人マネージャー1人 メリハリをつけた活動がモットー',
'火木土川内グラウンドにて活動中,マネージャー、プレイヤー共に大募集してます！',
'オンラインによる人狼、クイズ大会新歓を行っております。',
null,
'https://twitter.com/tonpeinanya',
null,
'東北大学学友会軟式野球部',
0
);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 email,
 twitter,
 instagram,
 picture_name,
 picture_num)
VALUES (
 5,
'競技麻雀同好会',
'学友会文化部準加盟団体',
'全学',
'定例会は毎週15人ほどが集まっており、男性がほとんどですが女性の方もいらっしゃいます。部室での交流は後期は週に2~3回鍵が貸し出されていました。土曜日以外は暇な人が来るようなものなので月に2~3回定例会に来れる方なら十分アクティブメンバー判定になります',
'毎週土曜日13時〜17時頃:定例会(これがメイン活動です) 不定期:部室やC棟を利用した講習 日常活動:各自部室で交流 その他:年に数度の大会出場や他大学との交流。当サークルは飲まない吸わない賭けないを掲げ活動しています。全国大会に出場する強者から大学から麻雀を始めた初心者向けまで様々な層が活動しています。是非気軽に質問や訪問してみてください。',
'例年は新歓期にC棟で説明と麻雀体験をして頂き、定例会へのお試し参加もしていました。今年はコロナウイルスの影響でそれらが延期されており現状オンラインでの新歓も予定していないため活動制限が解除されるまでは特に何もありません。Twitterでの質問等はいつでも受け付けておりますので気軽にお聞きください。',
'tohokumahjong@gmail.com',
'https://twitter.com/tonpei_mahjong',
null,
'競技麻雀同好会',
0
);

INSERT INTO circle(
 id,
 name,
 classification,
 organization,
 atmosphere,
 introduction,
 welcome_party_inf,
 email,
 twitter,
 instagram,
 picture_name,
 picture_num)
VALUES (
 6,
'東北大学 学友会 合気道部',
'学友会体育部',
'全学',
'学年ごとの人数・・・4年生7名 3年生 6名 2年生 12名 他留学生2名　男女比 約2：1　現在は理、工、文学部の部員が多く在籍しています(それ以外もいます！)',
'学友会合気道部では、川内キャンパスサブアリーナ3階アリーナ2にて稽古を行っています。週6日稽古がありますが、自分のペースで活動出来ます😄 また、部員の大半が大学から合気道を始めています。武道を始めてみたい方や体を動かしたい方など、初心者大歓迎です！！もちろん経験者も大歓迎です✨ どんな部活か気になった方は気軽に連絡くださいね。Twitterにて随時情報を発信してますのでぜひご確認よろしくお願いします！ 私たちと一緒に合気道をしましょう👍',
'LINEオープンチャットで質問等受け付けています！また、Zoomを用いたオンライン説明会も行います。その他、直接何か聞きたいことがありましたら、下記の新歓メールまでお問合せください！',
'tohokuaiki.welcome2020@gmail.com',
'https://twitter.com/TohokuaikiWago',
null,
'東北大学学友会合気道部',
7
);